name: dco-check
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  check_dco:
    runs-on: ubuntu-latest
    name: Check DCO
    steps:
      - name: Run dco-check
        uses: christophebedard/dco-check@ec8bfc43106afe98b323ace9133650df10497e12
        with:
          python-version: "3.14"
          args: "--verbose --exclude-pattern .*dependabot.*@users[.]noreply[.]github[.]com"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
